package com.fran.hibernateanotaciones3.entidades;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Escribir generated by hbm2java
 */
@Entity
@Table(name = "escribir")
public class Escribir implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private EscribirId id;
	private Autores autores;
	private Libros libros;
	private Integer anyo;

	public Escribir() {
	}

	public Escribir(EscribirId id, Autores autores, Libros libros) {
		this.id = id;
		this.autores = autores;
		this.libros = libros;
	}

	public Escribir(EscribirId id, Autores autores, Libros libros, Integer anyo) {
		this.id = id;
		this.autores = autores;
		this.libros = libros;
		this.anyo = anyo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codautor", column = @Column(name = "codautor", nullable = false, length = 5)),
			@AttributeOverride(name = "codlibro", column = @Column(name = "codlibro", nullable = false)) })
	public EscribirId getId() {
		return this.id;
	}

	public void setId(EscribirId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codautor", nullable = false, insertable = false, updatable = false)
	public Autores getAutores() {
		return this.autores;
	}

	public void setAutores(Autores autores) {
		this.autores = autores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codlibro", nullable = false, insertable = false, updatable = false)
	public Libros getLibros() {
		return this.libros;
	}

	public void setLibros(Libros libros) {
		this.libros = libros;
	}

	@Column(name = "anyo")
	public Integer getAnyo() {
		return this.anyo;
	}

	public void setAnyo(Integer anyo) {
		this.anyo = anyo;
	}

}
